### ISSUE TITLE
direct access url zertificate issues

### ISSUE THREAD

**Issue by jherrmann** [parse-community/parse-server-gcs-adapter#1]
Hi

there seems to be an issue with file URLs returned by parse server with GCS when direct access = true is set. 
I get (net::ERR_CERT_COMMON_NAME_INVALID) 
If line 133 is changed to it should work: 
`return `https://storage.googleapis.com/${this._bucket}/${this._bucketPrefix + filename}`;`

This is also the format the google cloud console returns if you use a public link.

**Comment by flovilmart** [comment]
Can you open a pull request please?

**Comment by jherrmann** [comment]
done^^
any idea how to get indirect access over https working? `config.mount` seams to return http even when  serverURL in parse server is set to https.

**Comment by flovilmart** [comment]
What do you mean by indirect access?

**Comment by jherrmann** [comment]
routed through parse-server when `directAccess` is set to false in the filesAdapter config
