### ISSUE TITLE
File is saved multiple times, and error is returned

### ISSUE THREAD

**Issue by natario1** [parse-community/parse-server-gcs-adapter#11]
I am trying to save a png image in a ParseFile from the android SDK. I do what I have always successfully done with parse.com. Just for reference:

```
ByteArrayOutputStream stream = new ByteArrayOutputStream();
bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream);
ParseFile imageParseFile = new ParseFile(filename, stream.toByteArray(), "image/png");
imageParseFile.saveInBackground();
```

The save operation fails after a while, with a `ParseRequestException` (code 100) caused by a `SocketTimeoutException`. At the same time, here’s what happens to parse-server:
- no error logs (running in verbose mode)
- 5 (not one) successful POST requests to parse/files/file.png
- file is, in fact, saved 5 times in my bucket

Any idea? I am 100% sure that save() is called just once. Somehow that is looped and repeated. Should I post this @ Parse-SDK-Android ?

**Comment by natario1** [comment]
I have spent the whole day at this and the Android SDK seems robust.

It makes the request, but no response is received, so it keeps POSTing due to a “retry” policy. It looks like parse-server is not issuing a response. Meanwhile in my logs I see these:

![screenshot](https://cloud.githubusercontent.com/assets/15526561/18566314/b0795b7e-7b93-11e6-98ac-6a56e4653222.png)

So these 201 do not reach my client. This happens only with some files, probably larger ones. If I save a simple text/plain log file, the response is received by Android. If I save images, it is not.

**Comment by eabadjiev** [comment]
@natario1 not sure if that is the case, but we found that Parse Android SDK has `5`-`10` sec timeouts, inc. READ_TIMEOUT and will aggressively retry to upload the file. Try increasing that timeout and see if it works.

FYI @btanev

**Comment by natario1** [comment]
@eabadjiev it might be? I have lost touch with this issue. If I remember correctly, it happened with PNG files, but it stopped when I moved to JPG. I don’t know.

I am pretty discouraged about the Android SDK.

**Comment by mtrezza** [comment]
Closing as outdated; there's a much newer GCP adapter available that this adapter should migrate to.
