### ISSUE TITLE
Seek for audio / video doesn't work

### ISSUE THREAD

**Issue by EricNetsch** [parse-community/parse-server-gcs-adapter#12]
@flovilmart 
Confirming this issue using the GCS Adapter.  My files seek/ buffer fine on googles side but not as PFfiles. Is there any recommended fix for GCS Adapter ??

Direct access works fine. But we want to continue using the indirect access dues to authentication restrictions.

**Comment by flovilmart** [comment]
Range headers have been implemented in parse-server for the grid store adapter: https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FilesRouter.js#L109

There will probably need a revamp to make it work with GCS, but I don't recommend you use that strategy as you'll consume resources to stream those files from the node.js process therefore preventing any other requests to go through properly... Direct access seems to be the best option for you, or using a custom front domain with nginx as a reverse proxy...

Also you could lift your authentication restrictions as basically PFFiles are public...

**Comment by jadsonlourenco** [comment]
@EricNetsch the best way is to use **Nginx** as front of your files, Parse-server authentication don't works for files just for the table that has the file name, so, if I know the file name I can access it using the Parse-server URL, even if the file is protected on Google Storage.

I don't have time this week to publish my Docker image for that, but I send you by email, let me know if solve your issue.
_(soon I will release this Docker Image public on Docker Hub)._

**Comment by EricNetsch** [comment]
@jadsonlourenco Thanks! That all makes sense I think Nginx is probably the best option at this point. Would be nice to be able to set ACL's on PFfiles in the future of parse-server.

I'll take a look at your gitlab project. Appreciate the invite!
