### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by marin-liovic** [parse-community/parse-server-gcs-adapter#24]
There are multiple security issues being reported by snyk https://snyk.io/test/npm/@parse/gcs-files-adapter/1.1.2
Can you please update your dependencies to latest versions or versions without security issues?

**Comment by TomWFox** [comment]
I don't have experience with snyk but it seems to be suggesting that there are no longer any vulnerabilities, so I think this can be closed.
<img width="656" alt="Screenshot 2019-03-30 at 12 28 12" src="https://user-images.githubusercontent.com/13188249/55276108-6829be80-52e7-11e9-8def-4c54ca74dd82.png">

**Comment by mtrezza** [comment]
Closing as outdated
