### ISSUE TITLE
Upgrade GCS library

### ISSUE THREAD

**Issue by lebenitza** [parse-community/parse-server-gcs-adapter#39]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-gcs-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-gcs-adapter/issues?q=is%3Aissue).

### Issue Description

Current version of @google-cloud/storage is 1.7.0 in the lock file, which is an outdated version from 4 years ago, which is a bit concerning. Latest version is 6.2.3.
We found out about this the hard way, as adding gcs-adapter downgraded google-auth-library and broke typescript compilation.

### Expected Outcome

Can we bring the library up to date?

**Comment by mtrezza** [comment]
Sure, please feel free to submit a PR.

**Comment by Moumouls** [comment]
@lebenitza i sent a PR: https://github.com/parse-community/parse-server-gcs-adapter/pull/40
