### ISSUE TITLE
Narrowing down gc dependencies

### ISSUE THREAD

**Issue by natario1** [parse-community/parse-server-gcs-adapter#9]
I’m new to this and I might be missing something, but what about narrowing down google dependencies?

We have a dependency on [google-cloud](https://github.com/GoogleCloudPlatform/google-cloud-node) which is **huge**, see /packages.
Looks like we only need [@google-cloud/storage](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/storage).

**Comment by flovilmart** [comment]
good call dare to open a PR?

**Comment by natario1** [comment]
Hey @flovilmart , done in #10 . Should be OK.

I think this is worth a new npm release - google-cloud alone is about 750mb and deploying is a pain (mine on GAE fails with a timeout error).

**Comment by flovilmart** [comment]
There will be a release in a few hours.

**Comment by natario1** [comment]
Hey @flovilmart , apart from this, why not making parse-server-modules a package of packages, just like [google-cloud](https://github.com/GoogleCloudPlatform/google-cloud-node) ? This way it could stay at ParsePlatform/parse-server-modules, which makes more sense.

**Comment by flovilmart** [comment]
@natario1 that's a great idea but I don't have access at large on the ParsePlatform organization so I can't efficiently create module, add contributors etc... (yet) and in a sense, that's OK, we could definitely gather all adapters in this repo and do the same. I would be a bit cautious as issue triage etc.. would be more complicated, but I'm open the the idea. 

BTW, I've added you as a member of the organization, so feel free to get started with that :)

There is a cool trick to merge repos with git without losing history by adding all the repos you wanna merge as remote, fetching them and then moving their content into a subfolder.

**Comment by natario1** [comment]
@flovilmart OK, thank you man. I’ll see what I can do.
